import type { IJobPost } from '@/features/job-board/types';
import type { IPost } from '@/features/board/types';

export const emptyJobPost: IJobPost = {
	postId: '',
	userId: '',
	userNickName: '',
	userProfileUrl: '',
	title: '',
	content: '',
	viewCount: 0,
	likeCount: 0,
	tags: [],
	attachments: [],
	likeUsers: [],
	bookmarkUsers: [],
	country: '',
	region: '',
	companyName: '',
	industry: '',
	experience: '',
	salary: '',
	workType: '',
	deadline: '',
	status: '',
	createdAt: new Date(),
};

export const emptyPost: IPost = {
	postId: '',
	title: '',
	content: '',
	userId: '',
	userProfileUrl: '',
	userNickName: '',
	comments: [],
	commentCount: 0,
	viewCount: 0,
	likeCount: 0,
	tags: [],
	attachments: [],
	likeUsers: [],
	bookmarkUsers: [],
	isPublic: '',
	country: '',
	region: '',
	category: '',
	status: '',
	createdAt: '',
};
