import { IJobPost, IPost } from '@/types/interface.ts'

export const emptyJobPost: IJobPost = {
  seq: 0,
  title: '',
  content: '',
  user: {
    seq: 0,
    nickName: '',
    email: '',
    profileImage: '',
    reportedCount: 0,
    reportedDate: '',
    country: '',
    interestCountry: '',
    region: '',
    userRole: '',
    userStatus: ''
  },
  viewCount: 0,
  likeCount: 0,
  tags: [],
  attachments: [],
  likeUsers: [],
  bookmarkUsers: [],
  country: '',
  region: '',
  industry: '',
  deadline: '',
  experience: '',
  salary: '',
  company: '',
  companyEmail: '',
  companyPhone: '',
  companyAddress: '',
  companyHomepage: '',
  companyLogo: '',
  status: '',
  createdAt: ''
}

export const emptyPost: IPost = {
  seq: 0,
  title: '',
  content: '',
  userSeq: 0,
  userProfileUrl: '',
  userNickName: '',
  comments: [],
  viewCount: 0,
  likeCount: 0,
  tags: [],
  attachments: [],
  likeUsers: [],
  bookmarkUsers: [],
  isPublic: '',
  country: '',
  region: '',
  category: '',
  status: '',
  createdAt: ''
}
